[package]
name = "vermale713/logger"
description = "A lightweight and easy-to-use logger utility for Roblox projects."
version = "0.1.1"
license = "Apache-2.0"
authors = ["vermale713"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
